{"version": "0.5", "lang": "python", "startTime": "1583657500202", "uuid": "954bed81-13ca-4826-b79f-0006564af256", "newcontainer": "0", "vmuptime": "1583651484", "platform": "AWS Lambda", "containerID": "2020/03/08/[$LATEST]692ff916440a44b1b73c9091cc677048", "functionName": "ServiceTwoPython", "functionMemory": "3008", "functionRegion": "us-east-1", "vmID": "yMGl3H", "linuxVersion": "#1 SMP Tue Aug 20 23:10:42 UTC 2019", "totalMemory": "3230668", "freeMemory": "3018652", "pageFaults": "2165301", "cpuType": "Intel(R) Xeon(R) Processor @ 2.50GHz - Model 62", "cpuModel": "62", "cpuUsr": "7878", "cpuNice": "0", "cpuKrn": "528", "cpuIdle": "1194207", "cpuIowait": "5", "cpuIrq": "0", "cpuSoftIrq": "113", "vmcpusteal": "93", "contextSwitches": "87640", "frameworkRuntime": "33", "endpoint": "admin17.cluster-cftyxgwyrild.us-east-1.rds.amazonaws.com", "bucketname": "project.bucket.tcss562.sps", "key": "edited_100000_Sales_Records.csv", "error2": "[1041; 'Database was unable to resume within timeout period.']", "userRuntime": "91283", "cpuUsrDelta": "32", "cpuNiceDelta": "0", "cpuKrnDelta": "9", "cpuIdleDelta": "18209", "cpuIowaitDelta": "0", "cpuIrqDelta": "0", "cpuSoftIrqDelta": "3", "vmcpustealDelta": "0", "contextSwitchesDelta": "3537", "pageFaultsDelta": "53703", "frameworkRuntimeDeltas": "16", "runtime": "91332", "endTime": "1583657591534", "2_thread_id": "16", "1_run_id": "0", "zAll": "Final Results:", "roundTripTime": "91988.96", "payload": "{\"bucketname\": \"project.bucket.tcss562.sps\"; \"key\": \"edited_100000_Sales_Records.csv\"; \"tablename\": \"SalesData\"; \"batchSize\": 1000; \"dbEndpoint\": \"admin17.cluster-cftyxgwyrild.us-east-1.rds.amazonaws.com\"; \"dbName\": \"DB_TCSS562\"}", "latency": "656.96", "runtimeOverlap": "3.81"}