{"version": "0.5", "lang": "python", "startTime": "1583661954502", "uuid": "50300b7e-fab2-43fc-aebf-c2e2ca318c39", "newcontainer": "1", "vmuptime": "1583656985", "platform": "AWS Lambda", "containerID": "2020/03/08/[$LATEST]f988738ab4fc4089ac5ad4a5cf580f6d", "functionName": "ServiceTwoPython", "functionMemory": "3008", "functionRegion": "us-east-1", "vmID": "pLr28f", "linuxVersion": "#1 SMP Tue Aug 20 23:10:42 UTC 2019", "totalMemory": "3230668", "freeMemory": "3073488", "pageFaults": "70837", "cpuType": "Intel(R) Xeon(R) Processor @ 2.50GHz - Model 62", "cpuModel": "62", "cpuUsr": "63", "cpuNice": "0", "cpuKrn": "108", "cpuIdle": "993584", "cpuIowait": "4", "cpuIrq": "0", "cpuSoftIrq": "0", "vmcpusteal": "27", "contextSwitches": "26742", "frameworkRuntime": "32", "endpoint": "admin50.cluster-cftyxgwyrild.us-east-1.rds.amazonaws.com", "bucketname": "project.bucket.tcss562.sps", "key": "edited_100000_Sales_Records.csv", "error2": "[1041; 'Database was unable to resume within timeout period.']", "userRuntime": "90992", "cpuUsrDelta": "32", "cpuNiceDelta": "0", "cpuKrnDelta": "31", "cpuIdleDelta": "18124", "cpuIowaitDelta": "0", "cpuIrqDelta": "0", "cpuSoftIrqDelta": "4", "vmcpustealDelta": "2", "contextSwitchesDelta": "4631", "pageFaultsDelta": "56494", "frameworkRuntimeDeltas": "14", "runtime": "91038", "endTime": "1583662045540", "2_thread_id": "49", "1_run_id": "0", "zAll": "Final Results:", "roundTripTime": "92513.0", "payload": "{\"bucketname\": \"project.bucket.tcss562.sps\"; \"key\": \"edited_100000_Sales_Records.csv\"; \"tablename\": \"SalesData\"; \"batchSize\": 1000; \"dbEndpoint\": \"admin50.cluster-cftyxgwyrild.us-east-1.rds.amazonaws.com\"; \"dbName\": \"DB_TCSS562\"}", "latency": "1475.0", "runtimeOverlap": "9.25"}